- hosts: gospodarsky
  become: yes
  tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: yes
    - name: Check if *** System Restart Required ***
      shell: "test -f /var/run/reboot-required"
      register: test_result
      ignore_errors: yes
    - name: Reboot a managed node if needed
      when: test_result.rc == 0
      reboot:
